CC=g++

LFLAGS=-lsfml-window -lsfml-graphics -lsfml-audio -lsfml-system
CFLAGS=-w

OBJS=wawacraft_tuxhart.cpp
TARGET=wawacraft_tuxhart.elf

wawacraft_tuxhart.elf: $(OBJS)
  $(CC) $(OBJS) $(CFLAGS) -o $(TARGET) $(LFLAGS)
